# Generated by Django 4.1.4 on 2023-12-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_desc_customuser_image_customuser_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('companyname', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('Number', models.BigIntegerField(blank=True, null=True)),
                ('Portfolio_amount', models.BigIntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('occupation', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Desc',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Portfolio_amount',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='occupation',
        ),
    ]
