# Generated by Django 4.1.4 on 2023-12-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='email',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
