# Generated by Django 4.1.4 on 2023-12-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('changesPercentage', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('dayLow', models.FloatField(blank=True, null=True)),
                ('dayHigh', models.FloatField(blank=True, null=True)),
                ('yearHigh', models.FloatField(blank=True, null=True)),
                ('yearLow', models.FloatField(blank=True, null=True)),
                ('marketcap', models.BigIntegerField(blank=True, null=True)),
                ('priceAvg50', models.FloatField(blank=True, null=True)),
                ('priceAvg200', models.FloatField(blank=True, null=True)),
                ('exchange', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('avgVolume', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('previousClose', models.FloatField(blank=True, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('earningsAnnouncement', models.DateField(blank=True, null=True)),
                ('sharesOutstanding', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
