# Generated by Django 4.1.4 on 2023-12-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cap',
            field=models.BooleanField(default=False),
        ),
    ]
