# Generated by Django 4.1.4 on 2023-12-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_stocks_data_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('changesPercentage', models.CharField(blank=True, max_length=30, null=True)),
                ('change', models.CharField(blank=True, max_length=30, null=True)),
                ('dayLow', models.CharField(blank=True, max_length=30, null=True)),
                ('dayHigh', models.CharField(blank=True, max_length=30, null=True)),
                ('yearHigh', models.CharField(blank=True, max_length=30, null=True)),
                ('yearLow', models.CharField(blank=True, max_length=30, null=True)),
                ('marketcap', models.BigIntegerField(blank=True, null=True)),
                ('cap', models.BooleanField(default=False)),
                ('priceAvg50', models.CharField(blank=True, max_length=30, null=True)),
                ('priceAvg200', models.CharField(blank=True, max_length=30, null=True)),
                ('exchange', models.CharField(blank=True, max_length=30, null=True)),
                ('volume', models.CharField(blank=True, max_length=30, null=True)),
                ('avgVolume', models.CharField(blank=True, max_length=30, null=True)),
                ('open', models.CharField(blank=True, max_length=30, null=True)),
                ('previousClose', models.CharField(blank=True, max_length=30, null=True)),
                ('pe', models.CharField(blank=True, max_length=30, null=True)),
                ('earningsAnnouncement', models.DateField(blank=True, null=True)),
                ('sharesOutstanding', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='stocks_data',
        ),
    ]
