# Generated by Django 4.1.4 on 2023-12-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_stock_data_delete_stocks_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_data',
            name='marketcap',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
