# Generated by Django 4.1.4 on 2023-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_stock_data_marketcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_data',
            name='earningsAnnouncement',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
